java_library(
    name = "fabdm",
    srcs = [
        "MainServlet.java",
        "UserServlet.java"
    ],
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "//src/main/java/com/fabdm/account",
        "//src/main/java/com/fabdm/template",
        "@guava//jar",
        "@javax_servlet_api//jar",
    ],
)