java_library(
    name = "editor",
    srcs = ["EditorServlet.java"],
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "//webapp/templates:editor",
        "@com_google_appengine_java//:user",
        "@guice//jar",
        "@javax_servlet_api//jar",
        "@soy//jar",
    ],
)
