java_library(
    name = "editor",
    srcs = ["EditorServlet.java"],
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "//src/main/java/com/kchodorow/diem/user",
        "//webapp/templates:editor",
        "@guice//jar",
        "@javax_servlet_api//jar",
        "@soy//jar",
    ],
)
