exports_files([
    "pin_joint.cc",
    "pin_joint.h",
])

filegroup(
    name = "pin-joint",
    srcs = [
        "pin_joint.cc",
        "pin_joint.h",
    ],
    visibility = ["//third_party/ammo.js:__pkg__"],
)
