// This file was autogenerated by js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/cloth.js', ['diem.Cloth'], ['diem.Fabric', 'diem.Particle'], false);
goog.addDependency('../../../../js/fabric.js', ['diem.Fabric'], [], false);
goog.addDependency('../../../../js/globals.js', ['diem.Globals'], [], false);
goog.addDependency('../../../../js/particle.js', ['diem.Particle'], ['diem.Fabric'], false);
goog.addDependency('../../../../js/person.js', ['diem.Person'], [], false);
goog.addDependency('../../../../js/ruler.js', ['diem.Ruler'], [], false);
