java_test(
    name = "pattern",
    srcs = ["SewingPatternPieceTest.java"],
    test_class = "com.fabricate.pattern.SewingPatternPieceTest",
    deps = [
        "//src/main/java/com/fabricate/math",
        "//src/main/java/com/fabricate/pattern",
        "@org_junit//jar",
    ],
)
