java_test(
    name = "RandomNameTest",
    srcs = glob(["RandomNameTest.java"]),
    deps = [
        "//src/main/java/com/fabdm/project",
        "@com_google_truth//jar",
        "@org_junit//jar",
    ]
)

java_test(
    name = "ModelTest",
    srcs = glob(["ModelTest.java"]),
    deps = [
        "//src/main/java/com/fabdm/project",
        "@com_google_truth//jar",
        "@org_junit//jar",
        "@guava//jar",
    ]
)

