java_library(
    name = "math",
    srcs = ["Vector2.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@auto_value//:jar",
        "@auto_value//:autovalue-plugin",
        "@guava//:guava",
    ],
)
