java_library(
    name = "math",
    srcs = [
        "AnchorPoint.java",
        "BezierCurve.java",
        "Vector2.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@auto_value//:jar",
        "@auto_value//:autovalue-plugin",
        "@guava//:guava",
    ],
)
