java_binary(
    name = "bundle",
    main_class = "does.not.exist",
    visibility = ["//:__pkg__"],
    runtime_deps = [
        "//src/main/java/com/kchodorow/diem/user",
        "//src/main/java/com/kchodorow/diem/editor",
    ],
)
