java_binary(
    name = "bundle",
    main_class = "does.not.exist",
    visibility = ["//:__pkg__"],
    runtime_deps = [
        "//src/main/java/com/kchodorow/diem",
        "//src/main/java/com/kchodorow/diem/editor",
        "//src/main/java/com/kchodorow/diem/project:servlet",
        "@org_tuckey_urlrewritefilter//jar",
    ],
)
