java_binary(
    name = "bundle",
    main_class = "does.not.exist",
    visibility = ["//:__pkg__"],
    runtime_deps = [
        "//src/main/java/com/fabdm",
        "//src/main/java/com/fabdm/account:servlet",
        "//src/main/java/com/fabdm/editor",
        "//src/main/java/com/fabdm/project:servlet",
        "@org_tuckey_urlrewritefilter//jar",
    ],
)
