java_library(
    name = "pattern",
    srcs = [
        "AnchorPoint.java",
        "CuttingLine.java",
        "InvalidPatternPieceException.java",
        "SewingPattern.java",
        "SewingPatternPiece.java",
    ],
    deps = [
        "@guava//:guava",
        "//src/main/java/com/fabricate/math",
    ],
    visibility = ["//src/test/java/com/fabricate/pattern:__pkg__"],
)
