java_library(
    name = "account",
    srcs = [
        "Account.java",
        "AccountStorage.java",
    ],
    deps = [
        "//src/main/java/com/kchodorow/diem/project",
        "@com_google_appengine_java//:user",
        "@com_google_objectify//jar",
        "@guava//jar",
        "@jsr305//jar",
        "@soy//jar",
    ],
    visibility = ["//src/main/java/com/kchodorow/diem:__subpackages__"],
)
