java_library(
    name = "editor",
    srcs = ["EditorServlet.java"],
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "//src/main/java/com/fabdm/template",
        "@com_google_appengine_java//:user",
        "@guava//jar",
        "@javax_servlet_api//jar",
    ],
)
