java_library(
    name = "template",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/com/kchodorow/diem/account",
        "@com_google_appengine_java//:user",
        "@guava//jar",
        "@soy//jar",
    ],
    visibility = ["//src/main/java/com/kchodorow/diem:__subpackages__"],
)
